package Exception_test;

/**
 * Created by IntelliJ IDEA.
 *
 * @Author : LiuDongBin
 * @create 2023/9/10 23:51
 */
public class Test1 {
    public static void main(String[] args) {
/*    1. java中所有的错误都继承自Throwable类，在该子类中，Error类表示严重的底层错误，一般处理方式是尽可能让程序终止，而Exception类表示例外，异常
       2.1 AlreadyBoundException属于已检查异常，必须处理
       2.2  PatternSyntaxException属于运行时异常，不需要处理
       3. throw new NullPointerException();
       throw new ClassCastException("类型转换出错");
       4.输出：
       main
       ma1
       mb1
       (对应数字的异常）(5没有异常，所以后面还会输出mb2 ma2)
       in finally
       main2



7. MyException要继承Exception
catch的顺序不对，应该从范围小的到大的

8.AB D
9.A
10. 100 100
11. ma1
ma2 1
In Finally

ma1
In Finally

12.不可以，问题出在MySub2，要考虑MySub2的异常是不是MySub的子类，这里不是，所以无法通过

13. B
14 B
        */

    }

}
